// Comprehensive collection of Latin typing terms
const latinTerms = [
    // Common phrases
    { term: "et cetera", meaning: "and the rest; and so forth", difficulty: "beginner" },
    { term: "ad hoc", meaning: "for this purpose; as needed", difficulty: "beginner" },
    { term: "vice versa", meaning: "the other way around; conversely", difficulty: "beginner" },
    { term: "per se", meaning: "by itself; in itself", difficulty: "beginner" },
    { term: "status quo", meaning: "the existing state of affairs", difficulty: "beginner" },
    { term: "alma mater", meaning: "nourishing mother; one's school or university", difficulty: "beginner" },
    { term: "bona fide", meaning: "in good faith; genuine", difficulty: "beginner" },
    { term: "circa", meaning: "approximately; around", difficulty: "beginner" },
    { term: "de facto", meaning: "in fact; in reality", difficulty: "beginner" },
    { term: "et alii", meaning: "and others", difficulty: "beginner" },
    
    // Intermediate terms
    { term: "carpe diem", meaning: "seize the day", difficulty: "intermediate" },
    { term: "cogito ergo sum", meaning: "I think, therefore I am", difficulty: "intermediate" },
    { term: "curriculum vitae", meaning: "course of life; résumé", difficulty: "intermediate" },
    { term: "deus ex machina", meaning: "god from the machine; unexpected solution", difficulty: "intermediate" },
    { term: "ergo", meaning: "therefore; consequently", difficulty: "intermediate" },
    { term: "habeas corpus", meaning: "you shall have the body; writ to produce prisoner", difficulty: "intermediate" },
    { term: "in memoriam", meaning: "in memory of", difficulty: "intermediate" },
    { term: "magna cum laude", meaning: "with great honor", difficulty: "intermediate" },
    { term: "modus operandi", meaning: "method of operating", difficulty: "intermediate" },
    { term: "non sequitur", meaning: "it does not follow; illogical conclusion", difficulty: "intermediate" },
    { term: "persona non grata", meaning: "unwelcome person", difficulty: "intermediate" },
    { term: "post mortem", meaning: "after death", difficulty: "intermediate" },
    { term: "prima facie", meaning: "at first sight; on the face of it", difficulty: "intermediate" },
    { term: "quid pro quo", meaning: "something for something; exchange", difficulty: "intermediate" },
    { term: "sine qua non", meaning: "without which not; essential condition", difficulty: "intermediate" },
    { term: "sub rosa", meaning: "under the rose; in secret", difficulty: "intermediate" },
    { term: "terra firma", meaning: "solid ground", difficulty: "intermediate" },
    { term: "verbatim", meaning: "word for word; exactly", difficulty: "intermediate" },
    { term: "vox populi", meaning: "voice of the people", difficulty: "intermediate" },
    { term: "ad infinitum", meaning: "to infinity; endlessly", difficulty: "intermediate" },
    
    // Advanced terms
    { term: "a fortiori", meaning: "from stronger reason; all the more", difficulty: "advanced" },
    { term: "a posteriori", meaning: "from the latter; based on observation", difficulty: "advanced" },
    { term: "a priori", meaning: "from the former; based on theory", difficulty: "advanced" },
    { term: "ad absurdum", meaning: "to the point of absurdity", difficulty: "advanced" },
    { term: "ad hominem", meaning: "to the person; personal attack", difficulty: "advanced" },
    { term: "ad nauseam", meaning: "to the point of nausea; excessively", difficulty: "advanced" },
    { term: "alter ego", meaning: "other self; close friend", difficulty: "advanced" },
    { term: "anno domini", meaning: "in the year of the Lord", difficulty: "advanced" },
    { term: "ante meridiem", meaning: "before midday", difficulty: "advanced" },
    { term: "ars longa vita brevis", meaning: "art is long, life is short", difficulty: "advanced" },
    { term: "caveat emptor", meaning: "let the buyer beware", difficulty: "advanced" },
    { term: "corpus delicti", meaning: "body of the crime; evidence", difficulty: "advanced" },
    { term: "de jure", meaning: "by law; legally", difficulty: "advanced" },
    { term: "exempli gratia", meaning: "for example", difficulty: "advanced" },
    { term: "ex libris", meaning: "from the books of", difficulty: "advanced" },
    { term: "ex post facto", meaning: "after the fact; retroactively", difficulty: "advanced" },
    { term: "in loco parentis", meaning: "in place of a parent", difficulty: "advanced" },
    { term: "in medias res", meaning: "into the middle of things", difficulty: "advanced" },
    { term: "in situ", meaning: "in position; in place", difficulty: "advanced" },
    
    // Expert level terms
    { term: "in toto", meaning: "in total; entirely", difficulty: "expert" },
    { term: "in vitro", meaning: "in glass; in a laboratory", difficulty: "expert" },
    { term: "in vivo", meaning: "in the living; in a living organism", difficulty: "expert" },
    { term: "ipso facto", meaning: "by the fact itself; thereby", difficulty: "expert" },
    { term: "lapsus linguae", meaning: "slip of the tongue", difficulty: "expert" },
    { term: "magnum opus", meaning: "great work; masterpiece", difficulty: "expert" },
    { term: "mea culpa", meaning: "my fault; I am to blame", difficulty: "expert" },
    { term: "memento mori", meaning: "remember you must die", difficulty: "expert" },
    { term: "mens rea", meaning: "guilty mind; criminal intent", difficulty: "expert" },
    { term: "mutatis mutandis", meaning: "with necessary changes; accordingly", difficulty: "expert" },
    { term: "non compos mentis", meaning: "not of sound mind", difficulty: "expert" },
    { term: "nota bene", meaning: "note well; pay attention", difficulty: "expert" },
    { term: "per annum", meaning: "by the year; annually", difficulty: "expert" },
    { term: "per capita", meaning: "by head; per person", difficulty: "expert" },
    { term: "post scriptum", meaning: "written after; postscript", difficulty: "expert" },
    { term: "pro bono", meaning: "for the public good; free work", difficulty: "expert" },
    { term: "pro forma", meaning: "for form; as a formality", difficulty: "expert" },
    { term: "pro rata", meaning: "proportionally; in proportion", difficulty: "expert" },
    { term: "pro tempore", meaning: "for the time being; temporarily", difficulty: "expert" },
    { term: "quantum meruit", meaning: "as much as deserved", difficulty: "expert" },
    { term: "quasi", meaning: "as if; seemingly", difficulty: "expert" },
    { term: "quod erat demonstrandum", meaning: "which was to be demonstrated", difficulty: "expert" },
    { term: "reductio ad absurdum", meaning: "reduction to absurdity", difficulty: "expert" },
    { term: "requiescat in pace", meaning: "may he/she rest in peace", difficulty: "expert" },
    { term: "semper fidelis", meaning: "always faithful", difficulty: "expert" },
    { term: "sic transit gloria mundi", meaning: "thus passes the glory of the world", difficulty: "expert" },
    { term: "sui generis", meaning: "of its own kind; unique", difficulty: "expert" },
    { term: "summa cum laude", meaning: "with highest honor", difficulty: "expert" },
    { term: "tabula rasa", meaning: "blank slate", difficulty: "expert" },
    { term: "tempus fugit", meaning: "time flies", difficulty: "expert" },
    { term: "terra incognita", meaning: "unknown land; unexplored territory", difficulty: "expert" },
    { term: "veni vidi vici", meaning: "I came, I saw, I conquered", difficulty: "expert" },
    { term: "versus", meaning: "against; toward", difficulty: "expert" },
    { term: "veto", meaning: "I forbid", difficulty: "expert" },
    { term: "viva voce", meaning: "with living voice; orally", difficulty: "expert" }
];
